version: '3.6'
services: 
  api:
    image: node:12.14.1
    container_name: handwritten-api
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 5015:5015
    command: npm start
    
